#!/usr/bin/with-contenv bash

# env check
if [[ -z "${PAS_PATH}" ]]; then
    export PAS_PATH="/usr/local/pas"
fi

# update from git
if [[ "${PAS_UPDATE}" == "true" ]]
then
    echo "[init-pas-config] Pulling PlexAutoSkip from github master"
    git config --global --add safe.directory ${PAS_PATH}
    git -C ${PAS_PATH} pull origin master --quiet
    ${PAS_PATH}/venv/bin/pip install -q --no-cache-dir -r ${PAS_PATH}/setup/requirements.txt --upgrade > /dev/null
fi

# permissions
chown -R abc:abc ${PAS_PATH}

exit $?
